import React from "react";
import styled from "styled-components";
import axios from "axios";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { useEffect, useContext, useState } from "react";
import UserContext from "../../context/UserContext";
import TrendingHashtag from "../TrendingHashtag/TrendingHashtag";
import { useParams } from "react-router-dom";
import dotenv from "dotenv";
import { IoHeart, IoHeartOutline } from "react-icons/io5";
